[project]
name = "executor-dao"
requirements = []

[repl]
costs_version = 2

[contracts.age000-governance-token]
path = "contracts/extensions/age000-governance-token.clar"
depends_on = ["executor-dao", "governance-token-trait", "trait-sip-010"]

[contracts.age001-proposal-voting]
path = "contracts/extensions/age001-proposal-voting.clar"
depends_on = ["executor-dao", "proposal-trait", "extension-trait", "governance-token-trait", "age000-governance-token"]

[contracts.age002-emergency-proposals]
path = "contracts/extensions/age002-emergency-proposals.clar"
depends_on = ["executor-dao", "extension-trait", "age001-proposal-voting"]

[contracts.age003-emergency-execute]
path = "contracts/extensions/age003-emergency-execute.clar"
depends_on = ["executor-dao", "extension-trait", "age001-proposal-voting"]

[contracts.agp000-bootstrap]
path = "contracts/proposals/agp000-bootstrap.clar"
depends_on = ["executor-dao", "proposal-trait", "extension-trait", "age000-governance-token", "age001-proposal-voting", "age002-emergency-proposals", "age003-emergency-execute"]

[contracts.agp001-kill-emergency-execute]
path = "contracts/proposals/agp001-kill-emergency-execute.clar"
depends_on = ["age003-emergency-execute", "executor-dao"]

[contracts.executor-dao]
path = "contracts/executor-dao.clar"
depends_on = ["proposal-trait", "extension-trait"]

[contracts.extension-trait]
path = "contracts/traits/extension-trait.clar"
depends_on = []

[contracts.governance-token-trait]
path = "contracts/traits/governance-token-trait.clar"
depends_on = []

[contracts.ownable-trait]
path = "contracts/traits/ownable-trait.clar"
depends_on = []

[contracts.proposal-trait]
path = "contracts/traits/proposal-trait.clar"
depends_on = []

[contracts.sip010-ft-trait]
path = "contracts/traits/sip010-ft-trait.clar"
depends_on = []

[contracts.alex-launchpad-v1-1]
path = "contracts_modules/alex_v1/pool/alex-launchpad-v1-1.clar"
depends_on = ["trait-sip-010", "trait-ido-ft", "token-apower"]

[contracts.token-wban]
path = "contracts_modules/alex_v1/wrapped-token/token-wban.clar"
depends_on = [ "trait-ownable", "trait-sip-010", "token-banana", "trait-ido-ft"]

[contracts.token-banana]
path = "contracts_modules/alex_v1/token/token-banana.clar"
depends_on = [ "trait-ownable", "trait-sip-010" ]

[contracts.trait-ownable]
path = "contracts_modules/alex_v1/traits/trait-ownable.clar"
depends_on = []

[contracts.trait-sip-010]
path = "contracts_modules/alex_v1/traits/trait-sip-010.clar"
depends_on = []

[contracts.trait-ido-ft]
path = "contracts_modules/alex_v1/traits/trait-ido-ft.clar"
depends_on = [ ]

[contracts.token-apower]
path = "contracts_modules/alex_v1/token/token-apower.clar"
depends_on = [ "trait-ownable", "trait-sip-010" ]

[contracts.token-wstx]
path = "contracts_modules/alex_v1/wrapped-token/token-wstx.clar"
depends_on = [ "trait-ownable", "trait-sip-010" ]

[contracts.agp029]
path = "alex-dao-proposals/contracts/agp029.clar"
depends_on = [ "alex-launchpad-v1-1", "token-wban", "age000-governance-token" ]

[contracts.agp030]
path = "alex-dao-proposals/contracts/agp030.clar"
depends_on = [ "alex-launchpad-v1-1", "token-wban", "age000-governance-token" ]

[contracts.agp031]
path = "alex-dao-proposals/contracts/agp031.clar"
depends_on = [ "alex-launchpad-v1-1", "token-wban", "age000-governance-token", "token-apower" ]





