[project]
name = "executor-dao"
requirements = []
costs_version = 2

[contracts.age000-governance-token]
path = "contracts/extensions/age000-governance-token.clar"
depends_on = ["executor-dao", "governance-token-trait", "sip010-ft-trait"]

[contracts.age001-proposal-voting]
path = "contracts/extensions/age001-proposal-voting.clar"
depends_on = ["executor-dao", "proposal-trait", "extension-trait", "governance-token-trait", "age000-governance-token"]

[contracts.age002-emergency-proposals]
path = "contracts/extensions/age002-emergency-proposals.clar"
depends_on = ["executor-dao", "extension-trait", "age001-proposal-voting"]

[contracts.age003-emergency-execute]
path = "contracts/extensions/age003-emergency-execute.clar"
depends_on = ["executor-dao", "extension-trait", "age001-proposal-voting"]

[contracts.agp000-bootstrap]
path = "contracts/proposals/agp000-bootstrap.clar"
depends_on = ["executor-dao", "proposal-trait", "extension-trait", "age000-governance-token", "age001-proposal-voting", "age002-emergency-proposals", "age003-emergency-execute"]

[contracts.agp001-kill-emergency-execute]
path = "contracts/proposals/agp001-kill-emergency-execute.clar"
depends_on = ["age003-emergency-execute", "executor-dao"]

[contracts.agp002-launchpad-alex]
path = "contracts/proposals/agp002-launchpad-alex.clar"
depends_on = ["proposal-trait"]

[contracts.executor-dao]
path = "contracts/executor-dao.clar"
depends_on = ["proposal-trait", "extension-trait"]

[contracts.extension-trait]
path = "contracts/traits/extension-trait.clar"
depends_on = []

[contracts.governance-token-trait]
path = "contracts/traits/governance-token-trait.clar"
depends_on = []

[contracts.ownable-trait]
path = "contracts/traits/ownable-trait.clar"
depends_on = []

[contracts.proposal-trait]
path = "contracts/traits/proposal-trait.clar"
depends_on = []

[contracts.sip010-ft-trait]
path = "contracts/traits/sip010-ft-trait.clar"
depends_on = []
